@echo off
echo Stopping any process on port 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":3000" ^| find "LISTENING"') do taskkill /f /pid %%a >nul 2>&1

echo Installing dependencies...
call npm install

echo Generating Prisma Client...
call npx prisma generate

echo Starting development server...
call npm run dev
